### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by demon-ru** [softandiron/tinkproject#1]
File "./main.py", line 245, in <module>
    my_positions = creating_positions_objects()
  File "./main.py", line 73, in creating_positions_objects
    percent_change = ((market_price / this_pos.average_position_price.value) * 100) - 100
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]

Похоже что пытается поделить на ноль. У меня есть акции VTRS, которые достались мне выделением от PFE по нулевой цене :)

**Comment by demon-ru** [comment]
Пока добавил проверку на 0 и... не придумал какой процент в этом случае ставить :)
Поставил 0%

**Comment by demon-ru** [comment]
И далее... вероятно, по этой же причине (по акции нет ни одной строки истории. Мне её "выделили", но я не покупал, не продавал).

Traceback (most recent call last):
  File "./main.py", line 248, in <module>
    my_positions = creating_positions_objects()
  File "./main.py", line 137, in creating_positions_objects
    ave_buy_price_rub = calculate_ave_buy_price_rub()
  File "./main.py", line 133, in calculate_ave_buy_price_rub
    ave_buy_price_rub = sum(item_list) / len(item_list)
ZeroDivisionError: division by zero

**Comment by EgoPingvina** [comment]
У меня тоже возник `ZeroDivisionError: division by zero` и экселька не появилась.

**Comment by Lowton** [comment]
К тому же в 130 строке. Добавил бы проверку на 0.
`ave_buy_price_rub = 0 if len(item_list) == 0 else sum(item_list) / len(item_list)`

**Comment by samizdam** [comment]
> К тому же в 130 строке main.py. Добавил бы проверку на 0.
> `ave_buy_price_rub = 0 if len(item_list) == 0 else sum(item_list) / len(item_list)`

https://github.com/softandiron/tinkproject/pull/5/commits/934e84aa62661b90dd14241aa037a1dc21ba2b56
