### ISSUE TITLE
Неверно вычет налога

### ISSUE THREAD

**Issue by glemag** [softandiron/tinkproject#11]
Странная ситуация, имею несколько рублевых акций, по одной, как ни странно по TCS имею положительную динамику. Но почему то в таблице налог считается не по **exp.yield**, а на всю сумму market value.

**Comment by softandiron** [comment]
Купил ради эксперимента TCS - у меня та же проблема. Буду искать причину.

**Comment by softandiron** [comment]
Я выяснил, что данная проблема вызвана тем, что у бумаги TCSG и у операций с ней почему-то разные figi:

![image](https://user-images.githubusercontent.com/83499138/118409318-6b27ca80-b679-11eb-8516-4937eb59b8ea.png)

**Comment by softandiron** [comment]
Проблема решена.
Приделал костыль, чтобы считал и TCS Group тоже.
 #e98f887

**Comment by softandiron** [comment]
Проблема решена.
Приделал костыль, чтобы программа считала и TCS Group тоже.

**Comment by glemag** [comment]
Добрый день, обновил, поправил, все заработало, спасибо.
