### ISSUE TITLE
Попробовать Банковское округление 

### ISSUE THREAD

**Issue by mikhashev** [softandiron/tinkproject#12]
https://github.com/softandiron/tinkproject/blob/8326f7675bf648340e02d44054ffc095598e6a2e/main.py#L54

Вероятно с этим связано небольшое расхождение, которое вы упоминали в статье.
Для корректного округления чисел попробовать Банковское округление. В Python функция round()

**Comment by softandiron** [comment]
Добился точности в 3 рубля на 9 000 000 за счёт загрузки market price (текущая рыночная стоимость бумаги) непосредственно с API вместо вычисления в программе из average buy price и expected yield. Только это на работает для облигаций из-за того, что для них из API рыночная цена приходит без НКД. Сли бы не это, точность была бы 100%.
Пока что точность будет зависить от того, сколько облигаций в портфеле. Если их нет - точность 100%. Больше облигаций - выше расхождение с данными в приложении.
