### ISSUE TITLE
Несколько счетов

### ISSUE THREAD

**Issue by webzlodimir** [softandiron/tinkproject#14]
Сейчас появилась возможность иметь несколько инвест счетов, было бы круто иметь возможность указать по какому счету получить статистику

**Comment by glemag** [comment]
Официальный ответ от TCS "Мультисчета пока не реализованы в API. Простите за неудобство"

Не уверен, но -  так как ID каждого счета имеет вид https://www.tinkoff.ru/invest/portfolio/ХХХХХХХХХХ/, где ХХХХХХХХХХ -  ID счета, то наверняка как то в API можно вывести данные по определенному счету.

**Comment by webzlodimir** [comment]
Значит будем ждать пока замутят в API, спасибо за ответ!
