### ISSUE TITLE
Очень не хватает столбца с названием акции которую купил/продал.

### ISSUE THREAD

**Issue by iLnurZ** [softandiron/tinkproject#16]
Возможно ли добавить столбец напротив даты операции с наименованием акции над которой произвелось действие. Что бы можно было отфильтровать конкретную акции и посмотреть когда продавал/покупал. Для анализа.

**Comment by softandiron** [comment]
Попробую сделать. У операций есть figi, значит, по ним можно найти, с какой бумагой операция проводилась.

**Comment by softandiron** [comment]
@iLnurZ Сделал. Посмотрите - как вам?

**Comment by iLnurZ** [comment]
> @iLnurZ Сделал. Посмотрите - как вам?

Спасибо большое, на домашнем компьютере почему то не получается установить питон, так что бы запускался проект, ругается, возможно я что-то не так делаю, не совсем понял как заполнить файл с датой, не нашел пример. На рабочем компьютере в понедельник проверю и отпишусь!

Traceback (most recent call last):
  File "E:\Downloads\tinkproject-2.0\main.py", line 14, in <module>
    import data_parser
  File "E:\Downloads\tinkproject-2.0\data_parser.py", line 143, in <module>
    account_data = parse_text_file()
  File "E:\Downloads\tinkproject-2.0\data_parser.py", line 101, in parse_text_file
    start_date = datetime(int(start_year), int(start_month), int(start_day), 0, 0, 0, tzinfo=my_timezone)
ValueError: invalid literal for int() with base 10: ''
>>>
