### ISSUE TITLE
Можно не парсить my_account.txt

### ISSUE THREAD

**Issue by alekskarrrl** [softandiron/tinkproject#24]
А зачем вам парсить файл my_account.txt ? Метод parse_text_file  не нужен, если все необходимые учетные данные сохранить в виде переменных в отдельном файле с расширением .py. Обычно это файл config.py или пускай будет  my_account.py

Пример файла config.py:

`# config.py`
`API_URL = 'https://YOUR_URL'`
`API_TOKEN = 'YOUR_API_TOKEN'`

Далее в  коде обращаетесь к переменной:
`config.API_TOKEN` 

И не забываем сделать импорт в файле, где обращаетесь к этим переменным
`import config` 

Файл config.py добавляете в .gitignore  так же как у вас там сейчас my_account.txt.

**Comment by evgkrsk** [comment]
Пожалуйста не надо перемешивать программу и обрабатываемые данные, это плохая практика.
