### ISSUE TITLE
Гайд

### ISSUE THREAD

**Issue by EgoPingvina** [softandiron/tinkproject#3]
Очень нехватает гайда, объясняющего на пальцах как запустить.
Всё заполнил, токен получил и внёс - выдаёт 500 ошибку. Как быть, кто виноват?)

**Comment by EgoPingvina** [comment]
1. Нужен токен "для торговли"
2. Должна быть отключена функция "Подтверждение сделок кодом"
В таком случае заработало.

**Comment by AuthorProxy** [comment]
кривые руки )
