### ISSUE TITLE
Некорректный loss после сплита акций

### ISSUE THREAD

**Issue by Thexmanrus** [softandiron/tinkproject#34]
Привет. Спасибо огромное за такой инструмент. Заметил, что при моих скромных 250к инвестиций, некий показатель loss равен почти -2,5M. Он почти целиком идет из tax base от акции, по которой был недавно сплит. Тут явно есть ошибка, хотя лично мне она сильно не мешает. Могу выслать excel файл для разбора, но не знаю куда. Еще раз спасибо за инструмент и хорошего дня =)

**Comment by alexanderkmd** [comment]
Привет!
Для начала просьба кинуть тикер бумаги, дату сплита, даты покупок.

**Comment by alexanderkmd** [comment]
> Привет. Спасибо огромное за такой инструмент. Заметил, что при моих скромных 250к инвестиций, некий показатель loss равен почти -2,5M. Он почти целиком идет из tax base от акции, по которой был недавно сплит. Тут явно есть ошибка, хотя лично мне она сильно не мешает. Могу выслать excel файл для разбора, но не знаю куда. Еще раз спасибо за инструмент и хорошего дня =)

Добрый день! Уточните пожалуйста, обновляли ли Вы версию программы? Потому что недавно было обновление #28, в том числе решающее проблему: #32, с вытекающей от сюда ошибкой расчета базы.

**Comment by Thexmanrus** [comment]
Прошу прощения, что пропал. Доступ к компу у меня на этой неделе только до
13 часов. Итак
2021 Aug 04  10:17 FXDE - 3 085,00   ₽
2021 Aug 04  10:16 FXDE   0,00   ₽
2021 Aug 03  10:08 FXDE   0,00   ₽
2021 Jul 27  16:55 FXDE - 3 082,50   ₽
2021 Jul 27  10:23 FXDE   0,00   ₽
2021 Jul 27  10:20 FXDE   0,00   ₽
2021 Jul 20  12:42 FXDE - 3 041,00   ₽
2021 Jul 14  11:03 FXDE   0,00   ₽
2021 Jul 06  10:22 FXDE   0,00   ₽
2021 Jul 05  10:05 FXDE   0,00   ₽
2021 Jun 14  10:41 FXDE - 12 548,00   ₽
2021 May 25  11:54 FXDE - 3 135,00   ₽ это все покупки, тикер тут же. сплит
был 9-го сентября

на данный момент прога выдает вот такой результат
[image: fxde.jpg]
Обновлялся вчера 14,09,2021 в 11.44
Я правильно понимаю, что надо скачать архив с tinkproject-2.5.zip и
разархивировать его с заменой файлов?

Только что проделал это еще раз. результат тот же, что на скрине.
Чем-то могу еще помочь ?

ср, 15 сент. 2021 г. в 06:32, Alexander Kozlov ***@***.***>:

**Comment by alexanderkmd** [comment]
Спасибо за пример покупок, будем их проверять.
Однако, последнюю версию лучше скачивать по данной ссылке: https://github.com/softandiron/tinkproject/archive/refs/heads/main.zip
Релизная версия, по-моему еще от середины августа. Просьба попробовать обновиться и проверить.

**Comment by Thexmanrus** [comment]
Да, в версии по ссылке все по видимому корректно! )
Спасибо. Работает.
И пользуясь возможностью хочу спросить, в апи Тинькова есть возможность
получать состав фондов по отраслям и странам? Я довольно далек от
программирования, и вопрос стоит ли вообще в эту сторону копать. Мне это
нужно для понимания диверсификации. Я пробовал парсить с сайта в таблицы
гугл, но что у тинька, что у финекса просто через importxml эти данные не
подтянуть. Пока в поиске решения.

чт, 16 сент. 2021 г. в 06:47, Alexander Kozlov ***@***.***>:

**Comment by softandiron** [comment]
Пока не нашёл такой возможности в текущем API. Возможно пофвится в новом API 2.0, который, насколько мне известно, сейчас находится в разработке.

**Comment by softandiron** [comment]
Я так понимаю, проблема решена. Спасибо @alexanderkmd
