### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by lbarmen** [softandiron/tinkproject#43]
`10:24:26 [INFO] ExBuild: content printing: Currencys                                                                    Traceback (most recent call last):                                                                                        File "C:\barmen\tinkoff\main.py", line 493, in <module>                                                                   build_excel_file(account, my_positions, my_operations, rates_today_cb, market_rate_today,                             File "C:\barmen\tinkoff\excel_builder.py", line 662, in build_excel_file                                                  last_row_pos = print_portfolio(1, 1)                                                                                  File "C:\barmen\tinkoff\excel_builder.py", line 203, in print_portfolio                                                   last_row = print_content("Currency")                                                                                  File "C:\barmen\tinkoff\excel_builder.py", line 150, in print_content                                                     row = print_position_data(row, col)                                                                                   File "C:\barmen\tinkoff\excel_builder.py", line 136, in print_position_data                                               'font_color': get_color(this_pos.percent_change)})                                                                    File "C:\barmen\tinkoff\classes.py", line 107, in percent_change                                                          return ((self.market_price / self.ave_price) * 100) - 100                                                           decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]     `

**Comment by IntelOut** [comment]
Вылазила такая ошибка по делению на ноль из-за пустого и не пополненного ИИСа.
 ```
Traceback (most recent call last):
  File "main.py", line 461, in <module>
    average_percent = get_average_percent()
  File "main.py", line 151, in get_average_percent
    return (sum(yield_list) / sum(sum_buy_list)) * 100
ZeroDivisionError: division by zero
```
Вылечил тем же способом что и выше. В main.py добавлена пара строчек перед строкой 151, проверяющих деление на ноль.
```
def get_average_percent():
    sum_buy_list, yield_list = [], []
    for this_pos in my_positions:
        if this_pos.currency in supported_currencies:
            sum_buy_list.append(this_pos.sum_buy * market_rate_today[this_pos.currency])
            yield_list.append(this_pos.exp_yield * market_rate_today[this_pos.currency])
        else:
            logger.warning(f'Unsupported currency: {this_pos.currency}')
    if sum(sum_buy_list) == 0:
        return 0
    return (sum(yield_list) / sum(sum_buy_list)) * 100
```

**Comment by alexanderkmd** [comment]
Благодарю за дополнение, добавил исправление в общий пул реквест #44.
