### ISSUE TITLE
Пустые сделки в отчете.

### ISSUE THREAD

**Issue by IntelOut** [softandiron/tinkproject#45]
Как советовали на Хабре.

"не хватает проверки статуса операции в create_operations_objects. В противном случае в отчете показываются и отмененные заявки"

Человет добавил пару строк в файл main.py (у меня это строка 312).

```
 for this_op in operations.payload.operations:
        if this_op.status != 'Done':
            continue
```

Добавил себе, прогнал. Реально помогло.
Рекомендую в прод.

**Comment by alexanderkmd** [comment]
Добрый день!

В отдельных случаях, наличие вывода "пустых" операций позволяет найти ошибки своего портфеля (что-то забыл купить или заявка не сработало, и не понимаешь, откуда лишний кэш), так что жесткая блокировка на уровне формирования файла - это не верно.

Как и с #46 - проблему можно решить путем формирования параметров при запуске, либо подробного конфиг-файла, если данные операции вам не нужны. Жесткое выпиливание их - это зло!

**Comment by alexanderkmd** [comment]
В реализации - проверку вставил на уровне формирования отчета, а не прохода по списку операций.

**Comment by IntelOut** [comment]
В ветке APIv2:
В конфиге при show empty operations: 'True' - отмененные сделки показываются в файле-результате.
show empty operations: 'False' - также показываются.

**Comment by alexanderkmd** [comment]
Добрый день @IntelOut !
Для ветки API2 эта опция переходит в разряд устаревших, поскольку в таблице сделок появилась фильтрация, позволяющая исключать пустые сделки на лету.
![image](https://user-images.githubusercontent.com/1858506/168968959-02f3f0c5-7ed9-4d6c-aa3f-10b689555a7d.png)

Не уверен, стоит ли вводить "принудительную" фильтрацию по наличию/значению этой опции в настройках.
