### ISSUE TITLE
Возможность отключения опроса по ИИС или брокерскому счету.

### ISSUE THREAD

**Issue by IntelOut** [softandiron/tinkproject#46]
В настоящий момент ИИС у меня пустой и в ближайшее время не планируется пополнение.
Однако, скрипт запрашивает по нему данные.

Идея следующая - сделать возможным выбрать какие портфели запрашивать.
Учитывая, что Тинькофф через какое-то время планирует добавить в апи возможность опрашивать по субпортфелям, такая фича была бы уместной.

**Comment by alexanderkmd** [comment]
Добрый!
Это надо решать на уровне запуска скрипта и передачи параметров, ну или подробного конфиг-файла. 
Скрипт действует по принципу: запроси список счетов/портфелей, по каждому из них собери файлик (файл main.py, строки 445-447). 
АПИ Тинькоф здесь не слишком влияет на логику.
