### ISSUE TITLE
Учет типа счета в формируемом отчете

### ISSUE THREAD

**Issue by supercep** [softandiron/tinkproject#47]
Привет!

Большая просьба добавить небольшое изменение для наглядного отображения типа счета в названии формируемого отчета

Заранее спасибо!

Ps
Возможно, оптимальным было бы с помощью тернарного оператора (предполагается изменение в строке 31 файла `excel_builder.py`) :
```python
excel_file_name = 'tinkoffReport_' + ('TinkoffIis_' if account.broker_account_type == 'TinkoffIis' else 'Tinkoff_') + data_parser.account_data['now_date'].strftime('%Y.%b.%d') + '_' ```

**Comment by alexanderkmd** [comment]
![image](https://user-images.githubusercontent.com/1858506/141972370-b277e88d-400a-4c5e-b0d4-c6612a7c33d9.png)
Ну примерно так это теперь может выглядеть!

**Comment by supercep** [comment]
Привет! 

Если доработка ожидает моего апрува, то это выглядит отлично, то, что и хотелось

Спасибо:)
