### ISSUE TITLE
Модули Python 3.9 для MacOS

### ISSUE THREAD

**Issue by EvelRus** [softandiron/tinkproject#52]
Добрый вечер.
Опытным путем обнаружил, что требуется доставить модули в терминале MacOS
`pip install scipy tinvest pycbrf xlsxwriter`

**Comment by alexanderkmd** [comment]
Добрый!

Да, данный факт отмечен в файле requirements.txt

**Comment by EvelRus** [comment]
Возможно, но мне это ни о чем не говорит...
В Вашей инструкции написано - скачать, создать файл с настройками, запустить команду python... Про зависимости не слово, ну или про то, что что-то надо ставить еще...
Поэтому и написал )
