### ISSUE TITLE
UnexpectedError: 401 при запуске

### ISSUE THREAD

**Issue by Starmont** [softandiron/tinkproject#60]
При запуске вылетает с ошибкой:
D:\tinkproject-main>python main.py                                                                                                                                                                                 00:37:15 [INFO] root: Start                                                                                                                                                                                        00:37:15 [INFO] Parser: getting accounts                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                   File "D:\tinkproject-main\main.py", line 451, in <module>                                                                                                                                                            accounts = data_parser.get_accounts()                                                                                                                                                                            File "D:\tinkproject-main\data_parser.py", line 68, in get_accounts                                                                                                                                                  accounts = client.get_accounts()                                                                                                                                                                                 File "C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\tinvest\clients.py", line 731, in get_accounts                                                                                                   return accounts_get(                                                                                                                                                                                             File "C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\tinvest\apis.py", line 394, in accounts_get                                                                                                      return request(                                                                                                                                                                                                  File "C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\tinvest\clients.py", line 537, in _request                                                                                                       raise UnexpectedError(response.status_code, response.text)                                                                                                                                                     tinvest.exceptions.UnexpectedError: 401              

файл my_account.txt состоит из след строчек:
t.3QQ_a8KQQuaCxaLPXXXXXXXXXXXXXXXXXXXXXXXXXXfJ_Iyl1R5G638ЧЧ5JWoS4_JP3dQ
Asia/Novosibirsk
2022
01
14

токен брал такой:  Все счета - Полный доступ

При этом не вижу появившегося лога. Пробовал с запустить с опцией -d => python -d main.py 
тоже лога не вижу.

**Comment by 3XclusiVe** [comment]
У меня была похожая проблема, Попробуйте отключить подтверждение операций кодом в лк тинькофф

**Comment by Starmont** [comment]
Отключено подтверждение. На всякий случай включил и отключил еще раз. Не помогло.

**Comment by 3XclusiVe** [comment]
И ещё один момент: проверьте yaml файл рядом с конфигом , насколько я понял он генерится только при первом исполнении и если вы меняли конфиг, то yaml файл не меняется.

**Comment by Starmont** [comment]
А вот это сработало!!! Спасибо за помощь!!  🤝
