### ISSUE TITLE
Дополнение для вывода информации по ИИС

### ISSUE THREAD

**Issue by ZIK-1337** [softandiron/tinkproject#8]
Дополнение к проекту автора, чтобы получать информацию по ИИС.
В файле data_parser.py в функции get_api_data прописываем строку print(client.get_accounts()) после строки print("- authorisation success"):
<img src="https://i.imgur.com/NoLGCY5.jpg" alt="image"/>
Затем запускаем main.py и потом можно нажать ctrl+c, чтобы остановить выполнение после получения нужных данных, а именно:
<img src="https://i.imgur.com/nL7co9P.jpg" alt="image"/>
Нам нужен broker_account_id от TinkoffIis, записываем его просто в код, а добавленную строчку удаляем:
<img src="https://i.imgur.com/ohIll8d.jpg" alt="image"/>
Можно записать также и id от брокерского, чтобы потом было проще менять в параметрах, пометив в комментарии, где иис, а где брокерский, после оставляя раскомменченным тот, который нужно запустить:
<img src="https://i.imgur.com/K43etUH.jpg" alt="image"/>
Теперь добавляем новый параметр broker_account_id=broker_account_id в 3 строки:
<img src="https://i.imgur.com/yklc3mL.jpg" alt="image"/>
И все, запускаем вновь main.py и получаем информацию по ИИС.

**Comment by softandiron** [comment]
Поступил комментарий брокера по поводу ИИС:
![image](https://user-images.githubusercontent.com/83499138/117511269-f370e600-af7c-11eb-9811-a33c8d66132c.png)

**Comment by softandiron** [comment]
Думаю, в следующей версии можно попробовать сделать, чтобы если счёта два, то программа на одном листе Excel формировала отчёт по ИИС, а на другом по обычному счёту. А на третьем листе ещё можно собрать общую статистику по обоим портфелям.
Проблема только в том, что мне не на чем проверять. ИИС в Тинькове я не могу открыть, потому что он у меня уже есть у другого брокера.

**Comment by ZIK-1337** [comment]
> Думаю, в следующей версии можно попробовать сделать, чтобы если счёта два, то программа на одном листе Excel формировала отчёт по ИИС, а на другом по обычному счёту. А на третьем листе ещё можно собрать общую статистику по обоим портфелям.
> Проблема только в том, что мне не на чем проверять. ИИС в Тинькове я не могу открыть, потому что он у меня уже есть у другого брокера.

Из комментария брокера как раз и изменял)
Думаю, не проблема, что нет ИИС, тут же вот достаточно параметр добавить, значение которого из запроса с помощью Json спарсится, а далее все то же самое.

**Comment by evgkrsk** [comment]
Создал альтернативную реализацию поддержки ИИС (#20).

**Comment by softandiron** [comment]
Проблему решил @evgkrsk (#20 )
